### PR TITLE
fix: checking passed config.log to be instance of winston.Logger

### LINKED ISSUE #626: Passing winston logger to config causes Error
```
const log = winston.createLogger();
const config = new SVGSpriterConfig({
    log,
});
```
throws
```
Uncaught TypeError: Function has non-object prototype 'undefined' in instanceof check
    at Function.[Symbol.hasInstance] (<anonymous>)
```
Because `winston.Logger` has no constructor

### PR DESCRIPTION
**Pull request by Kreeg**
Fixes #626

### CODE REVIEW

File: lib/svg-sprite/config.js [hunk 1]
```diff
@@ -13,12 +13,13 @@ const fs = require('fs');
 const path = require('path');
 const yaml = require('js-yaml');
 const winston = require('winston');
+const Logger = require('winston/lib/winston/logger.js');
```
[the remark this answers is not in the document]
Comment (Kreeg) [reply lib/svg-sprite/config.js:16]: No. But official exports has no Logger constructor. This behavior changed between v2 and v3 of package

[the remark this answers is not in the document]
Comment (XhmikosR) [reply lib/svg-sprite/config.js:16]: Hmm, unsure how proceed. It's just that this is fragile. Isn't there any other way to check for this?

[the remark this answers is not in the document]
Comment (Kreeg) [reply lib/svg-sprite/config.js:16]: I prefer to drop this checking of being instance of winston.Logger. Because the other part of `if` statement is checking of log is winston Logger but not an actual instance of `Logger`

File: lib/svg-sprite/config.js [hunk 2]
```diff
@@ -85,6 +85,19 @@ const defaultSVGConfig = {
...
 
+/**
+ * @param {any} logger  probable logger
+ * @returns {boolean}   result
+ */
+const isWinstonLogger = logger => {
+    return (
+        isObject(logger) &&
+        logger.level !== undefined &&
+        Array.isArray(logger.transports) &&
```
Comment (Kreeg) [inline lib/svg-sprite/config.js:96]: @XhmikosR here is the thing.
`lodash.isObject` returns true if array is passed. Our util is not. So there was an error here too because `transports` is an array

Comment (XhmikosR) [reply lib/svg-sprite/config.js:96]: Ouch... We might need to revisit our util then.

Comment (XhmikosR) [reply lib/svg-sprite/config.js:96]: BTW I prefer our isObject because it's tighter, but since we might have broken some stuff, better add a comment and accept Arrays too for now. We should revisit it later if needed.

Comment (Kreeg) [reply lib/svg-sprite/config.js:96]: Ok. I started to write tests. The goal is to cover entire project. This will find such errors. Our `isObject` is better, I agree
