### PR TITLE
Fix `shape.id.separator` regression

### LINKED ISSUE #740: bug: 2.0.0: `shape.id.separator` does not produce an `id` with the parent directory names
In 1.5.0 `shape.id.separator` traversed full directory path + file name into the shape ID. Now in 2.0.0 shape ID is always a svg file name, without any parent folders.

### PR DESCRIPTION
**Pull request by sfe-efficy**
Hi!

I created a fork to fix the problem reported here: #740

Regards

Fixes #740

### CODE REVIEW

File: lib/svg-sprite/shape.js [hunk 1]
```diff
@@ -149,14 +149,17 @@ function SVGShape(file, spriter) {
     this.spriter = spriter;
     this.svg = { current: this.source.contents.toString(), ready: null };
     this.name = path.basename(this.source.path);
+    // todo: get rid of setting empty object if this.spriter.config.shape is not provided
+    // https://github.com/svg-sprite/svg-sprite/pull/653#discussion_r841069781
     this.config = merge(merge({}, defaultConfig), this.spriter.config.shape || {});
-    // todo: get rid of setting empty object if this.spriter.config.shape is not provided (https://github.com/svg-sprite/svg-sprite/pull/653#discussion_r841069781)
+
+    const relativePath = this.source.base ? path.relative(this.source.base, this.source.path) : this.name;
```
Comment (Kreeg) [inline lib/svg-sprite/shape.js:156]: It's better be closer to where it's used (in this case, line 161)

File: test/svg-sprite/shape/shape.constructor.test.js [hunk 2]
```diff
@@ -158,6 +166,28 @@ describe('testing Shape.constructor', () => {
...
+                                meta: {},
+                                align: {}
+                            }
+                        },
+                        verbose: jest.fn()
+                    };
+                    const shape = new SVGShape(TEST_FILE_WITH_FOLDERS, TEST_SPRITER);
+
+                    expect(shape.config.id.generator(TEST_FILE_WITH_FOLDERS.relative)).toBe('folder--test_path.f');
+                    expect(path.relative(TEST_FILE_WITH_FOLDERS.base, TEST_FILE_WITH_FOLDERS.path)).toBe(TEST_FILE_WITH_FOLDERS.relative);
```
Comment (Kreeg) [inline test/svg-sprite/shape/shape.constructor.test.js:188]: This line is unnecessary because it testing the NodeJS functionality

File: lib/svg-sprite/shape.js (hunk 1 above)
Comment (sfe-efficy) [reply lib/svg-sprite/shape.js:156]: Yes! You're right

Comment (XhmikosR) [reply lib/svg-sprite/shape.js]: Done

File: test/svg-sprite/shape/shape.constructor.test.js (hunk 2 above)
Comment (sfe-efficy) [reply test/svg-sprite/shape/shape.constructor.test.js]: Changed to obtained the relative content from the content of the base path and full path.

**Review by Kreeg — APPROVED** [review]

**Comment by XhmikosR** [comment]
I'll try to backport this and cut a patch release because on main we have dropped Node.js 12 support.
